logging:
  file:
    name: "log-${spring.profiles.active}.txt"

spring:
  application:
    name: ms-backend
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  config:
    activate:
      on-profile: "!local"

api:
  message: 'You are using ${spring.profiles.active} profile'