server:
  port: 8089
  servlet:
    context-path: /api

logging:
  level:
    root: WARN
    com.company: DEBUG
  file:
    name: "log-${spring.profiles.active}.txt"

management:
  endpoints:
    web:
      exposure:
        include: [ "env", "health", "info" ]

spring:
  application:
    name: ms-backend
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

api:
  message: 'You are using ${spring.profiles.active} profile'