server:
    port: 8080
    servlet:
        context-path: /api
management:
    endpoints:
        web:
            exposure:
                include: [ "env", "health", "info" ]
spring:
    application:
        name: ms-backend-local
    messages:
        basename: i18n/messages
        encoding: UTF-8
    datasource:
        url: jdbc:h2:mem:testdb
    batch:
        initialize-schema: always
        job:
            enabled: false

logging:
    level:
        com.company: DEBUG
    file:
        name: log-local.txt

api:
    message:
        local: You are using local profile