server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: [ "env", "health", "info" ]
spring:
    application:
        name: ms-backend
    messages:
        basename: i18n/messages
        encoding: UTF-8
    datasource:
        url: jdbc:h2:mem:testdb

logging:
    level:
        com.company: DEBUG
